### ISSUE TITLE
this plugin should separate the plugin for volley and zxing

### ISSUE THREAD

**Issue by azizimusa** [MOLPay/molpay-mobile-xdk-android#1]
Instead of compile it together with Molpay sdk. It is better to separate them, so user can choose wether to include it or not. To prevent many duplicate entry in the future in gradle.

**Comment by clewlb** [comment]
@azizimusa,
We shipped google volley as the only dependancy for the MOLPay module to help make integrating MOLPay easier for any level of developers. For experience dev like yourself, we believe it should not be an issue to find duplicate dependancies in your project gradle and remove them accordingly. We hope this answers your concern over the duplicate dependancy issue. Thanks for your feedback.
