### ISSUE TITLE
Credit Card input UX improvement

### ISSUE THREAD

**Issue by andhie** [MOLPay/molpay-mobile-xdk-android#10]
### Problem Statement
With the current input flow when user keys in their credit card data, users are distracted while inputing data.

### Problem
When user selects Credit Card channel, there will be extra part of the form that will appear 
![screen shot 2017-02-17 at 10 33 38 pm](https://cloud.githubusercontent.com/assets/3997169/23070668/cfa4cbe4-f566-11e6-95ab-08f0e3e3c1d0.png)

Flow:
1) Put down phone and take out credit card from wallet
2) Pick up the phone and fills up card number
3) Next is the CVV row, user have to reach to their card and flip it to the back to view the CVV
4) Continue input CVV
5) Next is the Exp Date, which is in front of the card, user have to reach for their card and flip it again
6) Continue input Exp Date

### Proposal
I propose a minor order change in the input of Credit Card channel with the goal of improving UX.
Just by a simple row swap, users have much better experience filling up the form, where they only need to flip the card ONCE.

**Comment by clewlb** [comment]
@andhie,

Thanks for your feedback, we will definitely consider this constructive feedback for the improvement for our next major release.
