### ISSUE TITLE
mp_channel no value

### ISSUE THREAD

**Issue by azlandoctor2u** [MOLPay/molpay-mobile-xdk-android#12]
I'm trying to make FPX as the default channel. Here are the values I passed.

`paymentDetails.put(MOLPayActivity.mp_amount, mPrice);
        paymentDetails.put(MOLPayActivity.mp_username, getResources().getString(R.string.mp_username));
        paymentDetails.put(MOLPayActivity.mp_password, getResources().getString(R.string.mp_password));
        paymentDetails.put(MOLPayActivity.mp_merchant_ID, getResources().getString(R.string.mp_merchant_id));
        paymentDetails.put(MOLPayActivity.mp_app_name, getResources().getString(R.string.mp_app_name));
        paymentDetails.put(MOLPayActivity.mp_verification_key, getResources().getString(R.string.mp_verification_key));
        paymentDetails.put(MOLPayActivity.mp_order_ID, mRequestId);
        paymentDetails.put(MOLPayActivity.mp_currency, UserUtil.getHouseCallCurrency(mContext));
        paymentDetails.put(MOLPayActivity.mp_country, UserUtil.getHouseCountryISO2(mContext));
        paymentDetails.put(MOLPayActivity.mp_channel, "FPX");
        paymentDetails.put(MOLPayActivity.mp_bill_description, "Request a doctor to your doorstep");
        paymentDetails.put(MOLPayActivity.mp_bill_name, "Doctor House Call");
        paymentDetails.put(MOLPayActivity.mp_bill_email, UserUtil.getInstance(this).getEmail());
        paymentDetails.put(MOLPayActivity.mp_bill_mobile, UserUtil.getInstance(this).getPhone());
        paymentDetails.put(MOLPayActivity.mp_channel_editing, false);`

The problem is payment info still ask me to select a channel. "Please select a channel" still appear inside Pay through row instead of FPX. 
Actually what is the correct way to set default payment channel to FPX? I'm using the latest 3.11.0 version.

**Comment by clewlb** [comment]
@azlandoctor2u,

The channel value is case sensative, so please put "fpx". 

Thanks.
