### ISSUE TITLE
3.16.0 not work anymore

### ISSUE THREAD

**Issue by nguyenhuutinh** [MOLPay/molpay-mobile-xdk-android#13]
Hi team,
Yesterday I received some complains from user that they cannot use MOL payment.

I checked and faced same issue.
It worked before. 
compile 'com.molpay:molpay-mobile-xdk-android:3.16.0'

Any update from your side?

**Comment by clewlb** [comment]
Please update to 3.18.1. Thanks.

**Comment by nguyenhuutinh** [comment]
hi ,

Did you send us any email about these changes?
It affects our business because current payment doesnot work.

... and this is the second time we have to update library after received complains from our customers

**Comment by clewlb** [comment]
Please follow our repo if you want timely updates from us. Thanks.
