### ISSUE TITLE
after click on Proceed button, does not forward to bank page

### ISSUE THREAD

**Issue by azizimusa** [MOLPay/molpay-mobile-xdk-android#2]
Isn't it suppose to forward me to the bank login page? Currently all it return is json string like this 

`{"txn_ID":"7039867","paydate":1460015587,"order_id":"ss123","amount":"1.00","status_code":"11","channel":"MB2u","err_desc":"","app_code":"","chksum":"7ab215b01b5495483f2b10f5757a5c13","pInstruction":0,"msgType":"C6"}
`

**Comment by clewlb** [comment]
@azizimusa,
Please send us your MOLPay developer information to clement@molpay.com, we will take it from there. Thanks.
