### ISSUE TITLE
mp_verification_key =  Verify Key, any secure mode as last time?

### ISSUE THREAD

**Issue by ryusoft** [MOLPay/molpay-mobile-xdk-android#3]
this means our only verify key will be leaked, and hacker may potentially use the vkey to fake payment data, which means after the response send back, we may compulsory do a requery, am I right?

so is the "IsSecure" mode last time still valid? or any way for us not leaking the verify key?

**Comment by clewlb** [comment]
@ryusoft,

Our XDK will have all merchant's credentials encrypted with AES256 algorithm on runtime during the payment process. You can be assured that your verify key is protected against intruders when it is passed to the mobile XDK. Your app will only need to ensure fetching the verify key from a remote location in an encrypted format. If you have more concern on the security, please contact me at clement@molpay.com.

Thank you.

Clement
Head of Mobile
