### ISSUE TITLE
Cursor changes when enter the card number

### ISSUE THREAD

**Issue by nguyenhuutinh** [MOLPay/molpay-mobile-xdk-android#5]
Hi , when i enter the card number, the cursor is change to previous position. It is very hard to input .
Please check.
Thanks
Android 5.0.1

**Comment by clewlb** [comment]
@nguyenhuutinh,

Thanks for reaching out to us, please try our latest version 3.6.0, if the problem still persists, please contact me at clement@molpay.com.

Thanks.
