### ISSUE TITLE
How to handle event user cancel?

### ISSUE THREAD

**Issue by ericntd** [MOLPay/molpay-mobile-xdk-android#6]
The only way to close the MolPay activity is to tap the "Close" button on top right corner of the screen
RESULT_OK is always returns in `onActivityResult`
How can we differentiate between user complete the payment process and cancel halfway?

**Comment by clewlb** [comment]
@ericn37,

We only differentiate two scenarios, 1) Pre-transaction, 2) Post-transaction. 

For scenario 1, you would get a null status if the user canceled. 

For scenario 2, you'll get a status returned either in 00, 11, or 22. There are details on the variants of the failed status and can be found at the transaction details at the merchant portal.
 
If you have further questions about this, please email to support@molpay.com. We can assist you better through there.

Thanks.

MOLPay Mobile Team
