### ISSUE TITLE
SDK 3.9.0 crashes in MOLPayActivity#onCreate

### ISSUE THREAD

**Issue by andhie** [MOLPay/molpay-mobile-xdk-android#8]
Retrieve a non-existent key from a Map is guaranteed to return `null`. This is what causes the crash.

```java
paymentDetails = (HashMap<String, Object>) getIntent().getSerializableExtra(MOLPayPaymentDetails);

// For submodule wrappers
Boolean is_submodule = new Boolean(paymentDetails.get("is_submodule").toString());
String submodule_module_id = paymentDetails.get("module_id").toString();
String submodule_wrapper_version = paymentDetails.get("wrapper_version").toString();
if (is_submodule && submodule_module_id != null && submodule_wrapper_version != null) {
    ....
}
```

`paymentDetails.get("is_submodule")` will return `null` for sure and subsequent few lines.
Even so the if-statement does not make sense, if it was able `toString()` in the first place then `submodule_module_id` or `submodule_wrapper_version` will never be `null`

Below is a proposed fix for the bug. I have no idea what the value do yet, based on current way, the keys will always be null since users will never pass in such value.

```java
boolean is_submodule = false;
if (paymentDetails.containsKey("is_submodule")) {
    is_submodule = Boolean.valueOf(paymentDetails.get("is_submodule").toString());
}
String submodule_module_id = null;
if (paymentDetails.containsKey("module_id")) {
    submodule_module_id = paymentDetails.get("module_id").toString();
}
String submodule_wrapper_version = null;
if (paymentDetails.containsKey("wrapper_version")) {
    submodule_wrapper_version = paymentDetails.get("wrapper_version").toString();
}
... 
```

Its amazing that such a critical bug can slip thru testing, since it crashes even before its able display anything.

**Comment by clewlb** [comment]
@andhie, we must admit that it was the worst mistake we could ever make, we have released V3.9.1 based on your feedback. We would like to take this opportunity to thank you for the first hand info, and it could've been an inconvenience when this get exposed to more developments out there. Please feel free to review us more often in the future. Again, thanks for all!

**Comment by andhie** [comment]
Thank you for the quick response. I forgot there is still a subtle bug in my proposed fix.
Should also check for `null` value even if a key is present or else `paymentDetails.get()` will still return `null`.

```java
if (paymentDetails.containsKey("module_id") && paymentDetails.get("module_id") != null) {
    submodule_module_id = paymentDetails.get("module_id").toString();
}
```

Since the keys `is_submodule`, `module_id`, and `wrapper_version` is guaranteed not present in the mapping, it will not cause a crash (for now). Out of curiosity, may i know how is those key/value is suppose to be set?

**Comment by clewlb** [comment]
@andhie, glad you asked, the three parameters are only used in internal integration when one needs to work on a wrapper library that wraps this module. For now, it's only used by MOLPay internal team, so we can safely assume this would never creates a concern to the public. Your earlier suggested fix have been sufficient in our opinion. Thanks for asking!
